openapi: 3.0.0
info:
  title: Educational Content API
  description: API for accessing educational content in the Physical AI & Humanoid Robotics textbook
  version: 1.0.0
  contact:
    name: Textbook Development Team

paths:
  /modules:
    get:
      summary: List all available modules
      description: Returns a list of all educational modules in the textbook
      responses:
        '200':
          description: List of modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'

  /modules/{moduleId}:
    get:
      summary: Get module details
      description: Returns detailed information about a specific module
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
          description: ID of the module
      responses:
        '200':
          description: Module details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
        '404':
          description: Module not found

  /modules/{moduleId}/chapters:
    get:
      summary: List chapters in a module
      description: Returns a list of all chapters in a specific module
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
          description: ID of the module
      responses:
        '200':
          description: List of chapters in the module
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'
        '404':
          description: Module not found

  /modules/{moduleId}/chapters/{chapterId}:
    get:
      summary: Get chapter content
      description: Returns the content of a specific chapter
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
          description: ID of the module
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
          description: ID of the chapter
      responses:
        '200':
          description: Chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Module or chapter not found

components:
  schemas:
    Module:
      type: object
      required:
        - id
        - title
        - description
        - targetAudience
        - estimatedDuration
        - learningObjectives
        - chapters
      properties:
        id:
          type: string
          description: Unique identifier for the module
          example: "module-01-introduction"
        title:
          type: string
          description: Title of the module
          example: "Introduction to Physical AI & Humanoid Robotics"
        description:
          type: string
          description: Brief description of the module
          example: "Foundational module introducing Physical AI concepts, embodied intelligence, and humanoid robotics"
        targetAudience:
          type: string
          description: Intended audience for the module
          example: "Beginners to early-intermediate learners with basic programming knowledge"
        estimatedDuration:
          type: string
          description: Estimated time to complete the module
          example: "4-6 hours"
        learningObjectives:
          type: array
          description: List of learning objectives for the module
          items:
            type: string
          example:
            - "Understand what Physical AI is and how it differs from traditional AI"
            - "Explain the concept of embodied intelligence"
            - "Identify key components of humanoid robots"
        chapters:
          type: array
          description: List of chapters in the module
          items:
            $ref: '#/components/schemas/ChapterSummary'

    ChapterSummary:
      type: object
      required:
        - id
        - title
        - description
        - estimatedDuration
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
          example: "01-what-is-physical-ai"
        title:
          type: string
          description: Title of the chapter
          example: "What is Physical AI?"
        description:
          type: string
          description: Brief description of the chapter
          example: "Introduction to Physical AI as AI systems that interact with the real world through sensors and actuators"
        estimatedDuration:
          type: string
          description: Estimated time to complete the chapter
          example: "1-2 hours"

    Chapter:
      type: object
      required:
        - id
        - title
        - moduleId
        - sections
        - learningObjectives
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
          example: "01-what-is-physical-ai"
        title:
          type: string
          description: Title of the chapter
          example: "What is Physical AI?"
        moduleId:
          type: string
          description: ID of the parent module
          example: "module-01-introduction"
        description:
          type: string
          description: Brief description of the chapter
          example: "Introduction to Physical AI as AI systems that interact with the real world through sensors and actuators"
        sections:
          type: array
          description: Content sections in the chapter
          items:
            $ref: '#/components/schemas/ContentSection'
        learningObjectives:
          type: array
          description: Learning objectives for this chapter
          items:
            type: string
          example:
            - "Define Physical AI"
            - "Distinguish between software-only AI and Physical/Embodied AI"
            - "Identify the role of perception, action, and feedback loops in Physical AI systems"
        estimatedDuration:
          type: string
          description: Estimated time to complete the chapter
          example: "1-2 hours"

    ContentSection:
      type: object
      required:
        - type
        - title
        - content
      properties:
        type:
          type: string
          description: Type of content section
          enum: [Introduction, Core Concepts, Examples, Summary]
          example: "Core Concepts"
        title:
          type: string
          description: Title of the content section
          example: "Core Concepts"
        content:
          type: string
          description: Content of the section in Markdown format
          example: "Physical AI refers to AI systems that interact with the real world through sensors and actuators..."
        examples:
          type: array
          description: Examples or scenarios in this section
          items:
            type: string
          example:
            - "Self-driving cars use cameras and sensors to perceive their environment"
            - "Warehouse robots navigate and manipulate objects in physical space"