"""
ChatResponse data model for the RAG Chatbot API.

This module defines the ChatResponse Pydantic model for representing
responses generated by the AI system.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field
from .retrieved_chunk import RetrievedChunk


class Citation(BaseModel):
    """
    Data model representing a citation in a response.
    """
    text: str = Field(
        ...,
        description="The cited text snippet",
        example="Humanoid robots are robots with physical characteristics resembling humans..."
    )
    page_url: str = Field(
        ...,
        description="URL of the source page",
        example="https://example.com/textbook/module-01-introduction"
    )
    module: str = Field(
        ...,
        description="Module name of the source",
        example="module-01-introduction"
    )
    chapter: str = Field(
        ...,
        description="Chapter name of the source",
        example="introduction-to-humanoid-robotics"
    )
    section: str = Field(
        ...,
        description="Section name of the source",
        example="what-is-humanoid-robotics"
    )


class ChatResponse(BaseModel):
    """
    Data model representing a chat response from the AI system.
    """
    response_id: str = Field(
        ...,
        description="Unique identifier for the response",
        example="response-12345"
    )
    query_id: str = Field(
        ...,
        description="ID of the query this response is for",
        example="query-12345"
    )
    session_id: str = Field(
        ...,
        description="ID of the session this response belongs to",
        example="session-12345"
    )
    answer: str = Field(
        ...,
        description="The generated answer text",
        example="Humanoid robots are robots with physical characteristics resembling humans..."
    )
    citations: List[Citation] = Field(
        default_factory=list,
        description="List of source citations used in the response"
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the response was generated"
    )
    tokens_used: Optional[int] = Field(
        default=None,
        description="Number of tokens used in generating the response"
    )
    response_time_ms: Optional[int] = Field(
        default=None,
        description="Time taken to generate the response in milliseconds"
    )
    metadata: Optional[dict] = Field(
        default=None,
        description="Additional metadata for the response"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "response_id": "response-12345",
                "query_id": "query-12345",
                "session_id": "session-12345",
                "answer": "Humanoid robots are robots with physical characteristics resembling humans...",
                "citations": [
                    {
                        "text": "Humanoid robots are robots with physical characteristics resembling humans...",
                        "page_url": "https://example.com/textbook/module-01-introduction",
                        "module": "module-01-introduction",
                        "chapter": "introduction-to-humanoid-robotics",
                        "section": "what-is-humanoid-robotics"
                    }
                ],
                "timestamp": "2023-10-20T10:00:00Z",
                "tokens_used": 150,
                "response_time_ms": 2500,
                "metadata": {"model": "gemini-1.5-pro"}
            }
        }