"""Embedding data model."""
from dataclasses import dataclass
from typing import List
from datetime import datetime


@dataclass
class Embedding:
    """
    Vector representation of a content segment generated by Cohere Embed.
    """
    id: str
    content_segment_id: str
    vector: List[float]
    model_name: str
    created_at: datetime = datetime.now()

    def __post_init__(self):
        """Validate the embedding after initialization."""
        if not self.vector:
            raise ValueError("Vector must not be empty")

        if not self.content_segment_id:
            raise ValueError("Content segment ID must not be empty")

        if not self.model_name:
            raise ValueError("Model name must not be empty")