# API Contract: Humanoid Systems & HRI Content for RAG Integration
# This defines how the educational content will be structured for RAG system integration

openapi: 3.0.0
info:
  title: Humanoid Systems & HRI Educational Content API
  description: API contracts for Module 7 content integration with RAG system
  version: 1.0.0

paths:
  /content/hri/kinematics-dynamics:
    get:
      summary: Get content about humanoid kinematics and dynamics
      description: Retrieve educational content about degrees of freedom, forward/inverse kinematics, and center of mass concepts
      responses:
        '200':
          description: Educational content about kinematics and dynamics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HRIContent'
              example:
                module: "Module 7"
                chapter: "Humanoid Kinematics & Dynamics"
                concepts:
                  - "Degrees of freedom (DoF)"
                  - "Forward & inverse kinematics"
                  - "Center of mass (CoM)"
                  - "Dynamics vs statics"
                examples:
                  - "Kinematic chain of a humanoid leg"
                  - "Visual diagram showing joint hierarchy"
                learning_objectives:
                  - "Understand humanoid kinematics concepts"
                  - "Describe balance and stability constraints"

  /content/hri/bipedal-locomotion:
    get:
      summary: Get content about bipedal locomotion and balance
      description: Retrieve educational content about gait cycles, ZMP, and balance control
      responses:
        '200':
          description: Educational content about bipedal locomotion and balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HRIContent'
              example:
                module: "Module 7"
                chapter: "Bipedal Locomotion & Balance"
                concepts:
                  - "Gait cycles"
                  - "Zero Moment Point (ZMP)"
                  - "Static vs dynamic walking"
                  - "Fall detection and recovery"
                examples:
                  - "Conceptual walking pipeline"
                  - "Balance control loop diagram"
                learning_objectives:
                  - "Reason about bipedal walking"
                  - "Explain gait cycles and center-of-mass control"

  /content/hri/manipulation-grasping:
    get:
      summary: Get content about manipulation and grasping
      description: Retrieve educational content about grasp types, end-effectors, and reachability
      responses:
        '200':
          description: Educational content about manipulation and grasping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HRIContent'
              example:
                module: "Module 7"
                chapter: "Manipulation & Grasping"
                concepts:
                  - "End-effectors"
                  - "Grasp types (power vs precision)"
                  - "Visual servoing"
                  - "Reachability constraints"
                examples:
                  - "Object pickup pipeline"
                  - "Grasp selection logic (diagrammatic)"
                learning_objectives:
                  - "Understand grasping strategies"
                  - "Connect perception to manipulation"

  /content/hri/human-robot-interaction:
    get:
      summary: Get content about human-robot interaction
      description: Retrieve educational content about social robotics, proxemics, and safety
      responses:
        '200':
          description: Educational content about human-robot interaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HRIContent'
              example:
                module: "Module 7"
                chapter: "Human–Robot Interaction (HRI)"
                concepts:
                  - "Social robotics principles"
                  - "Proxemics and safety zones"
                  - "Multi-modal interaction"
                  - "Ethical and safety considerations"
                examples:
                  - "Human–robot interaction flow"
                  - "Error-handling scenarios (human interrupt)"
                learning_objectives:
                  - "Create safe, intuitive interaction models"
                  - "Evaluate interaction modalities (speech, gesture, vision)"

components:
  schemas:
    HRIContent:
      type: object
      required:
        - module
        - chapter
        - concepts
        - examples
        - learning_objectives
      properties:
        module:
          type: string
          description: The module identifier
          example: "Module 7"
        chapter:
          type: string
          description: The chapter title
          example: "Humanoid Kinematics & Dynamics"
        concepts:
          type: array
          items:
            type: string
          description: Key concepts covered in the chapter
          example: ["Degrees of freedom (DoF)", "Forward & inverse kinematics"]
        examples:
          type: array
          items:
            type: string
          description: Practical examples included in the chapter
          example: ["Kinematic chain of a humanoid leg", "Visual diagram showing joint hierarchy"]
        learning_objectives:
          type: array
          items:
            type: string
          description: Learning objectives for the chapter
          example: ["Understand humanoid kinematics concepts", "Describe balance and stability constraints"]
        semantic_chunks:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              content:
                type: string
              tags:
                type: array
                items:
                  type: string
          description: Semantic chunks for RAG system integration