# ROS 2 Interfaces for Educational Content

# This document describes the ROS 2 interfaces that learners will implement
# in Module 2: ROS 2 — The Robotic Nervous System

openapi: 3.0.0
info:
  title: ROS 2 Educational Interfaces
  description: ROS 2 interfaces and message types that learners will implement in the textbook
  version: 1.0.0
  contact:
    name: Textbook Development Team

# ROS 2 Node Interface
paths:
  /nodes:
    get:
      summary: List available ROS 2 nodes
      description: Returns a list of active ROS 2 nodes in the system
      responses:
        '200':
          description: List of active nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeInfo'

  /nodes/{node_name}:
    get:
      summary: Get node details
      description: Returns detailed information about a specific node
      parameters:
        - name: node_name
          in: path
          required: true
          schema:
            type: string
          description: Name of the node
      responses:
        '200':
          description: Node details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInfo'
        '404':
          description: Node not found

# Topics interface
  /topics:
    get:
      summary: List available topics
      description: Returns a list of available ROS 2 topics
      responses:
        '200':
          description: List of topics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicInfo'

# Services interface
  /services:
    get:
      summary: List available services
      description: Returns a list of available ROS 2 services
      responses:
        '200':
          description: List of services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceInfo'

# Actions interface
  /actions:
    get:
      summary: List available actions
      description: Returns a list of available ROS 2 actions
      responses:
        '200':
          description: List of actions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActionInfo'

components:
  schemas:
    NodeInfo:
      type: object
      required:
        - name
        - namespace
        - publishers
        - subscribers
        - services
        - actions
      properties:
        name:
          type: string
          description: Name of the node
          example: "publisher_node"
        namespace:
          type: string
          description: Namespace of the node
          example: "/"
        publishers:
          type: array
          description: List of publishers in the node
          items:
            $ref: '#/components/schemas/PublisherInfo'
        subscribers:
          type: array
          description: List of subscribers in the node
          items:
            $ref: '#/components/schemas/SubscriberInfo'
        services:
          type: array
          description: List of services provided by the node
          items:
            $ref: '#/components/schemas/ServiceServerInfo'
        actions:
          type: array
          description: List of actions provided by the node
          items:
            $ref: '#/components/schemas/ActionServerInfo'

    TopicInfo:
      type: object
      required:
        - name
        - type
        - publishers_count
        - subscribers_count
      properties:
        name:
          type: string
          description: Name of the topic
          example: "/chatter"
        type:
          type: string
          description: Message type of the topic
          example: "std_msgs/msg/String"
        publishers_count:
          type: integer
          description: Number of publishers on this topic
          example: 1
        subscribers_count:
          type: integer
          description: Number of subscribers on this topic
          example: 1

    ServiceInfo:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          description: Name of the service
          example: "/add_two_ints"
        type:
          type: string
          description: Service type
          example: "example_interfaces/srv/AddTwoInts"

    ActionInfo:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          description: Name of the action
          example: "/fibonacci"
        type:
          type: string
          description: Action type
          example: "example_interfaces/action/Fibonacci"

    PublisherInfo:
      type: object
      required:
        - topic
        - type
      properties:
        topic:
          type: string
          description: Topic name this publisher publishes to
          example: "/chatter"
        type:
          type: string
          description: Message type
          example: "std_msgs/msg/String"

    SubscriberInfo:
      type: object
      required:
        - topic
        - type
      properties:
        topic:
          type: string
          description: Topic name this subscriber subscribes to
          example: "/chatter"
        type:
          type: string
          description: Message type
          example: "std_msgs/msg/String"

    ServiceServerInfo:
      type: object
      required:
        - service
        - type
      properties:
        service:
          type: string
          description: Service name
          example: "/add_two_ints"
        type:
          type: string
          description: Service type
          example: "example_interfaces/srv/AddTwoInts"

    ActionServerInfo:
      type: object
      required:
        - action
        - type
      properties:
        action:
          type: string
          description: Action name
          example: "/fibonacci"
        type:
          type: string
          description: Action type
          example: "example_interfaces/action/Fibonacci"

# ROS 2 Message Types
# These represent the message types that learners will use in their examples
  schemas:
    MessageTypes:
      type: object
      description: Common ROS 2 message types used in examples
      properties:
        std_msgs:
          type: object
          description: Standard message types
          properties:
            String:
              type: string
              description: String message type
              example: "Hello, ROS 2!"
            Int32:
              type: integer
              description: 32-bit integer message type
              example: 42
            Float64:
              type: number
              description: 64-bit float message type
              example: 3.14
        geometry_msgs:
          type: object
          description: Geometry message types
          properties:
            Twist:
              type: object
              description: Velocity commands
              properties:
                linear:
                  type: object
                  properties:
                    x:
                      type: number
                      example: 1.0
                    y:
                      type: number
                      example: 0.0
                    z:
                      type: number
                      example: 0.0
                angular:
                  type: object
                  properties:
                    x:
                      type: number
                      example: 0.0
                    y:
                      type: number
                      example: 0.0
                    z:
                      type: number
                      example: 0.5
        sensor_msgs:
          type: object
          description: Sensor message types
          properties:
            JointState:
              type: object
              description: Joint state information
              properties:
                name:
                  type: array
                  items:
                    type: string
                  example: ["joint1", "joint2"]
                position:
                  type: array
                  items:
                    type: number
                  example: [0.5, 1.0]
                velocity:
                  type: array
                  items:
                    type: number
                  example: [0.0, 0.0]
                effort:
                  type: array
                  items:
                    type: number
                  example: [0.0, 0.0]