# Content Structure Contract for Module 4: The Digital Twin: Gazebo & Unity Simulation

openapi: 3.0.0
info:
  title: Module 4 Content Structure API
  description: Contract defining the structure and requirements for digital twin simulation content
  version: 1.0.0

paths: {}

components:
  schemas:
    Chapter:
      type: object
      required:
        - id
        - title
        - sections
        - learning_objectives
        - prerequisites
      properties:
        id:
          type: string
          description: Chapter identifier (e.g., "01-digital-twin-concepts")
          pattern: "^[0-9]{2}-[a-z0-9-]+$"
        title:
          type: string
          description: Chapter title
        sections:
          type: array
          items:
            $ref: "#/components/schemas/Section"
          minItems: 4
          maxItems: 4
        learning_objectives:
          type: array
          items:
            type: string
          description: List of learning objectives for the chapter
        prerequisites:
          type: array
          items:
            type: string
          description: Prerequisites from previous modules/chapters
        duration_estimate:
          type: number
          description: Estimated time to complete in minutes

    Section:
      type: object
      required:
        - type
        - content
        - learning_goals
      properties:
        type:
          type: string
          enum: [Introduction, Concepts, Examples, Summary]
          description: Section type following the required template
        content:
          type: string
          description: Markdown content for the section
        learning_goals:
          type: array
          items:
            type: string
          description: Specific learning goals for this section
        diagrams:
          type: array
          items:
            $ref: "#/components/schemas/Diagram"
          description: Diagrams to be included in the section

    Diagram:
      type: object
      required:
        - id
        - title
        - type
        - description
      properties:
        id:
          type: string
          description: Unique diagram identifier
        title:
          type: string
          description: Diagram title
        type:
          type: string
          enum: [mermaid, ascii, image_reference]
          description: Type of diagram representation
        description:
          type: string
          description: Description of what the diagram illustrates
        content:
          type: string
          description: The actual diagram content

    Example:
      type: object
      required:
        - title
        - type
        - description
        - expected_outcome
      properties:
        title:
          type: string
          description: Example title
        type:
          type: string
          enum: [demonstration, exercise, checklist, analysis]
          description: Type of example
        description:
          type: string
          description: Detailed description of the example
        complexity:
          type: string
          enum: [simple, moderate, complex]
          description: Complexity level
        required_tools:
          type: array
          items:
            type: string
          description: Tools required for the example
        expected_outcome:
          type: string
          description: What the learner should achieve
        validation_steps:
          type: array
          items:
            type: string
          description: Steps to validate the example worked

    SimulationPlatform:
      type: object
      required:
        - name
        - type
        - features
        - ros2_integration
      properties:
        name:
          type: string
          enum: [Gazebo, Unity]
          description: Name of the simulation platform
        type:
          type: string
          enum: [Physics-Based, Visualization-Focused, Hybrid]
          description: Primary focus of the platform
        features:
          type: array
          items:
            type: string
          description: Key features of the platform
        ros2_integration:
          type: boolean
          description: Whether the platform supports ROS 2 integration
        use_cases:
          type: array
          items:
            type: string
          description: Typical use cases for this platform
        tradeoffs:
          type: object
          properties:
            advantages:
              type: array
              items:
                type: string
            disadvantages:
              type: array
              items:
                type: string

    Concept:
      type: object
      required:
        - name
        - definition
        - examples
      properties:
        name:
          type: string
          description: Concept name
        definition:
          type: string
          description: Clear definition of the concept
        examples:
          type: array
          items:
            type: string
          description: Examples that illustrate the concept
        related_concepts:
          type: array
          items:
            type: string
          description: Other concepts related to this one
        applications:
          type: array
          items:
            type: string
          description: Practical applications of this concept
        validation:
          type: boolean
          description: Whether this concept can be validated through examples

  examples:
    digitalTwinChapter:
      summary: Example of a Chapter object
      value:
        id: "01-digital-twin-concepts"
        title: "Digital Twins & Simulation Concepts"
        learning_objectives:
          - "Explain what a digital twin is and its role in Physical AI"
          - "Differentiate between simulation and emulation"
          - "Describe the sim-to-real gap and why humanoids need high-fidelity simulation"
        prerequisites:
          - "Module 3: Robot Modeling & Simulation Fundamentals"
        duration_estimate: 120
        sections:
          - type: "Introduction"
            content: "Welcome to digital twin concepts..."
            learning_goals:
              - "Understand the purpose of digital twins in robotics"
          - type: "Concepts"
            content: "Core concepts of digital twins..."
            learning_goals:
              - "Define digital twin terminology"
          - type: "Examples"
            content: "Practical examples of digital twins..."
            learning_goals:
              - "Apply digital twin concepts"
          - type: "Summary"
            content: "Key takeaways from this chapter..."
            learning_goals:
              - "Synthesize learning from this chapter"

    gazeboPlatform:
      summary: Example of a Simulation Platform object
      value:
        name: "Gazebo"
        type: "Physics-Based"
        features:
          - "Realistic physics simulation"
          - "Collision detection"
          - "Sensor simulation"
          - "ROS 2 integration"
        ros2_integration: true
        use_cases:
          - "Physics-based robot testing"
          - "Control algorithm validation"
          - "Sensor fusion testing"
        tradeoffs:
          advantages:
            - "Realistic physics modeling"
            - "Strong ROS 2 ecosystem"
            - "Accurate collision detection"
          disadvantages:
            - "Less advanced graphics"
            - "Resource intensive"
            - "Steeper learning curve"